game_homepage:
    path:     /
    defaults: { _controller: GameBundle:Default:index }

game_play:
    path:     /recibe-jugada/{jugador}/{posicion}
    defaults: { _controller: GameBundle:Default:recibeJugada }
    methods: GET

game_restart:
    path:     /reiniciar-juego
    defaults: { _controller: GameBundle:Default:reiniciarJuego }
    methods: GET
