game_homepage:
    path:     /
    defaults: { _controller: GameBundle:Default:index }

game_test:
    path:     /recibe-jugada/{jugador}/{posicion}
    defaults: { _controller: GameBundle:Default:recibeJugada }
    methods: GET
